language: elixir
elixir:
  - 1.5
install:
  - cp config/client_secret.json.example config/client_secret.json
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
otp_release:
  - 19.1
script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
